spring:
  application:
    name: cloud-zuul

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ignored-services: "*"
  strip-prefix: true  #请求转发时去掉转发路径（path中的值）
  routes:
    project:  #所有以/console开头的请求都转发到app-console-web应用
      path: /project/**
      serviceId: project
    project1:  #所有以/console开头的请求都转发到app-console-web应用
      path: /project1/**
      serviceId: project1